name: linting-pipeline

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        npm install --save-dev htmlhint stylelint

    - name: Lint HTML files
      run: npx htmlhint "**/*.html"

    - name: Lint CSS Files
      run: |
        if ls **/*.css 1> /dev/null 2>&1; then
          npx stylelint "**/*.css" || echo "No CSS files to lint or linting failed"
        else
          echo "No CSS files found, skipping linting"
        fi

    - name: Lint contents of Package.json
      run: cat package.json
